src/components/MainSideBar/index.tsx, src/pages/ContestPage.tsx, src/router.tsx
=> feat: 학생협업공모전 페이지 구현

.github/workflows/deploy-production.yml, src/pages/ContestPage.tsx
=> ci: 환경변수 설정 변경

src/components/Card/CalenderCard.tsx, src/components/Card/NoticeCard.tsx, src/components/Timetable/TimetableItem.tsx, src/pages/LoginPage.tsx
- 로그인 계정 오류 시 아이디, 비밀번호가 모두 비어지는 문제
- 공지사항 줄바꿈을 지원하지 않음
- 시간표, 학사일정에서 underline 스타일을 제거했습니다.
- 로그인 계정 오류 시 비밀번호 칸만 비어지도록 변경하였습니다.
- 공지사항 줄바꿈 기능을 추가하였습니다.
=> fix: UI/UX 개선

src/error/ErrorMessage.ts
=> fix: update ErrorMessage.ts

public/index.html
- IE 경고 메세지가 제대로 안뜨는 오류
- 오류 수정 및 IE 오류 메세지 수정
=> fix: update index.html for IE

src/pages/ContestPage.tsx
=> fix: update text of ContestPage

package.json, src/api/index.ts, src/components/Card/QRCodeCard.tsx, src/components/MainSideBar/index.tsx, src/components/Timetable/TimetableItem.tsx, src/pages/ContestPage.tsx, src/pages/LoginPage.tsx, src/pages/RegisterPage.tsx, src/pages/UmbrellaPage.tsx, yarn.lock
=> fix: 알림창에 있는 이모지 제거

package.json, src/components/MainSideBar/index.tsx, src/components/Register/RegisterForm.tsx, src/pages/AccountPage.tsx, src/router.tsx, src/styles/global.css, yarn.lock
- 회원가입 페이지에서 학과, 학년, 번호가 string 타입으로 결정되는 문제
- input 태그에서 string으로 결정됨
- 회원가입 페이지에서 string이 아닌 number으로 결정되도록 수정
- 내 정보 페이지 구현
- 로그아웃 시 메인페이지 이동 후 처리되게 수정
=> feat: 내 정보 페이지 구현

README.md, package.json, src/pages/TimetablePage.tsx, src/utils/Converter/SchoolNumber.ts, yarn.lock
=> fix: 시간표 페이지 내 박스 크기 수정

public/index.html
=> feat: add console image

src/pages/UmbrellaPage.tsx
=> fix: 우산 반납 시간 변경 (6시)

src/components/MainTitleBar/MyInfoTitle.tsx, src/components/Timetable/TimetableItem.tsx, src/utils/Converter/Department.ts
=> fix: fix typo

src/components/MainSideBar/index.tsx
=> style: remove unused import code

public/firebase-messaging-sw.js, src/components/Card/CalenderCard.tsx, src/components/Card/MealCard.tsx, src/components/Card/NoticeCard.tsx, src/components/Card/TimetableCard.tsx, src/components/Card/WeatherCard.tsx, src/resources/push.ts
=> feat: 푸시 알림 클릭 이벤트 추가

public/index.html
=> test: remove console text

public/index.html, src/resources/push.ts
- 브라우저에서 Notification (with firebase) 미지원 시 알림 설정을 안하도록 수정
=> fix: 브라우저 호환성 확인 추가

src/pages/RegisterPage.tsx
- 회원가입시 이름에 한글, 영어 외 입력할 수 없도록 하였습니다.
=> fix: add name form filter(regexp)

src/components/Register/RegisterForm.tsx
=> fix: delete 기타 option in RegisterPage form

public/index.html
=> chore: apply google tag manager

src/components/Timetable/TimetableItem.tsx
=> feat: add class into TimetableItem for GTM

src/components/MainSideBar/index.tsx
=> feat:Self-diagnosis

src/components/MainSideBar/index.tsx, src/pages/EventPage.tsx, src/router.tsx
- 런칭 이벤트 당첨 확인 페이지 구현
- 당첨자 데이터는 백엔드가 아닌 프론트엔드가 갖고 있음.
=> feat: 런칭 이벤트 당첨 확인 페이지 구현

public/firebase-messaging-sw.js
=> fix: 푸시 알림이 두 번 보내지는 오류 수정

public/index.html
=> chore: add tagmanger code

src/components/LoginHelpModal/index.tsx, src/pages/LoginPage.tsx, src/pages/RegisterPage.tsx
=> feat: add help message into login and register pages

src/components/Register/RegisterForm.tsx, src/components/Register/RegisterHeaderText.tsx, src/pages/LoginPage.tsx
- autofocus 를 추가하여 페이지 로딩 시 자동으로 포커스가 가도록 수정
=> fix: 로그인, 회원가입 접근성 개선

package.json, src/components/LoginHelpModal/index.tsx, src/components/MainSideBar/index.tsx, src/components/MainTitleBar/MyInfoTitle.tsx, src/components/MainTitleBar/index.tsx, src/styles/global.css, yarn.lock
- 데스크탑 사이드바 디자인을 변경하였습니다.
- 일부 메뉴를 제거하였습니다.
- 신규 서비스를 추가 안내를 위해 메뉴를 추가하였습니다.
- 사이드바 Active 스타일을 구현했습니다.
- 로그인 & 회원가입 시 도움말 Modal 문구를 수정했습니다.
- `sinamon-sikhye` v2.0.0 업그레이드
=> feat: 사이드바 디자인 변경

src/resources/push.ts
=> fix: Web Push 버그 수정 (Apple 대응)

.github/workflows/deploy-production.yml
=> chore: 서비스 주소 변경

public/firebase-messaging-sw.js, src/resources/push.ts
=> fix: 푸시 알림에 새로운 도메인 적용

public/index.html
=> chore: 애널리틱스 코드 변경

src/pages/AnonymousPage.tsx, src/router.tsx
=> feat: AnonymousPage
